version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html 
    networks:
      - local_network
  nginx:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
    - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - local_network

  db:
    build:
      context: ./DB
      dockerfile: Dockerfile 
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: astraconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1607
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    entrypoint: ["docker-entrypoint.sh", "postgres"]
    networks:
      - local_network
networks:
  local_network:
    driver: bridge

volumes:
  db_data: